name: my_first_workflow

on:
  push:
    branches: 
      - main
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: greetings
        run: echo "Hello people" Welcome to programming
  job-two:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: introduction
         run: echo "Programming is giving commands to a computer to run a specific task"
