name: my_first_workflow

on:
  push:
    branches: 
      - main
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: greetings
        run: echo "Hello people" Welcome to programming
